apiVersion: v1
kind: Service

metadata:
  namespace: singouins-dev
  name: sep-backend-loadbalancer
  labels:
    tier: sep-backend
spec:
  type: LoadBalancer
  selector:
    app: nginx
    tier: sep-backend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
