apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins-dev
  name: sep-backend-redis-commander
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
      tier: sep-backend
  template:
    metadata:
      labels:
        app: redis-commander
        tier: sep-backend
    spec:

      containers:
      - name: sep-backend-redis-commander
        image: rediscommander/redis-commander:latest
        resources:
          limits:
            memory: 64Mi
            cpu: 50m
          requests:
            memory: 32Mi
            cpu: 10m
        env:
        - name: REDIS_HOSTS
          value: DEV:sep-backend-redis-svc:6379:1
        # Work around k8s specificas to allow pod replacement with 0 downtime.
        - name: K8S_SIGTERM
          value: '1'
        ports:
        - name: redis-commander
          containerPort: 8081
