apiVersion: v1
kind: Service

metadata:
  namespace: singouins-dev
  name: sep-backend-redis-commander-svc
  labels:
    tier: sep-backend
spec:
  selector:
    app: redis-commander
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 8081
