apiVersion: v1
kind: Service

metadata:
  namespace: singouins-dev
  name: sep-backend-prometheus-svc
  labels:
    tier: sep-backend
spec:
  selector:
    app: prometheus-server
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    name: default
  clusterIP: None
