{
 "title": "App | Flask (API) Dashboard [DEV]",
 "tags": [
  "Flask",
  "prometheus",
  "singouins"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "MEM / CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"api\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "gauge",
   "description": "API MEM Usage / ALL MEM Usage",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{app=\"api\",kubernetes_namespace=\"singouins-dev\"}) / sum(container_memory_working_set_bytes{namespace=\"singouins-dev\",pod=~\"^sep-backend.*\",container!=\"\"})*100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=\"api\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "App Commit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "singouins_info{app=\"api\"}",
     "legendFormat": "{{ commit }}"
    }
   ]
  },
  {
   "title": "App version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "singouins_info{app=\"api\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\",method=~\"GET|POST|DELETE\",app=\"api\"}[30s])",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(flask_http_request_total{app=\"api\"}[1m])",
     "legendFormat": "{{ method }} HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!~\"200|201\",app=\"api\"}[30s]))",
     "legendFormat": "status!=200"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{method=\"GET\",app=\"api\"}[30s]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{method=\"POST\",app=\"api\"}[30s]))",
     "legendFormat": "POST"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{method=\"DELETE\",app=\"api\"}[30s]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Requests response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\",app=\"api\"}[30s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\",app=\"api\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Requests under 500ms",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(increase(flask_http_request_duration_seconds_bucket{status=\"200\",le=\"0.5\",app=\"api\"}[30s]) \n/ ignoring (le) increase(flask_http_request_duration_seconds_count{status=\"200\",app=\"api\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration (p50)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(flask_http_request_duration_seconds_bucket{status=\"200\",app=\"api\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration (p90)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{status=\"200\",app=\"api\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}