apiVersion: v1
kind: Service

metadata:
  namespace: singouins-dev
  name: sep-backend-resolver-svc
  labels:
    tier: sep-backend
spec:
  selector:
    app: resolver
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 3000
    name: resolver
