apiVersion: v1
kind: Service

metadata:
  namespace: singouins-dev
  name: sep-backend-mariadb-svc
spec:
  selector:
    app: mariadb
    tier: sep-backend
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
  - name: metrics
    port: 9104
    protocol: TCP
  clusterIP: None
