apiVersion: v1
kind: ConfigMap
metadata:
  name: sep-backend-redis-conf
  namespace: singouins-dev
data:
  redis-conf: |
    # Don't use more memory than the specified amount of bytes.
    # When the memory limit is reached Redis will try to remove keys
    # according to the eviction policy selected (see maxmemory-policy).
    maxmemory 32mb

    # MAXMEMORY POLICY: how Redis will select what to remove when maxmemory
    # is reached. You can select among five behaviors:
    #
    # volatile-lru -> remove the key with an expire set using an LRU algorithm
    # allkeys-lru -> remove any key according to the LRU algorithm
    # volatile-random -> remove a random key with an expire set
    # allkeys-random -> remove a random key, any key
    # volatile-ttl -> remove the key with the nearest expire time (minor TTL)
    # noeviction -> don't expire at all, just return an error on write operations
    maxmemory-policy noeviction

    # Keyspace notifications allow clients to subscribe to Pub/Sub channels in
    # order to receive events affecting the Redis data set in some way.
    # K     Keyspace events, published with __keyspace@<db>__ prefix.
    # E     Keyevent events, published with __keyevent@<db>__ prefix.
    # g     Generic commands (non-type specific) like DEL, EXPIRE, RENAME, ...
    # $     String commands
    # l     List commands
    # s     Set commands
    # h     Hash commands
    # z     Sorted set commands
    # t     Stream commands
    # d     Module key type events
    # x     Expired events (generated every time a key expires)
    # e     Evicted events (generated when a key is evicted for maxmemory)
    # m     Key miss events (generated when a key that doesn't exist is accessed)
    # A     Alias for "g$lshztxed", so "AKE" means all the events except "m".
    notify-keyspace-events s$xE

    # Set the number of databases. The default database is DB 0, you can select
    # a different one on a per-connection basis using SELECT <dbid> where
    # dbid is a number between 0 and 'databases'-1
    databases 2
